# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tftg256-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/mark01/CESEL-CW305-test/CESEL-CW305-test.cache/wt [current_project]
set_property parent.project_path /home/mark01/CESEL-CW305-test/CESEL-CW305-test.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /home/mark01/CESEL-CW305-test/CESEL-CW305-test.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog /home/mark01/CESEL-CW305-test/board.v
set_property file_type "Verilog Header" [get_files /home/mark01/CESEL-CW305-test/board.v]
read_verilog -library xil_defaultlib {
  /home/mark01/CESEL-CW305-test/CESEL_test.v
  /home/mark01/CESEL-CW305-test/usb_module.v
  /home/mark01/CESEL-CW305-test/registers.v
  /home/mark01/CESEL-CW305-test/cw305_top.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/mark01/CESEL-CW305-test/cw305_main.xdc
set_property used_in_implementation false [get_files /home/mark01/CESEL-CW305-test/cw305_main.xdc]


synth_design -top cw305_top -part xc7a100tftg256-2


write_checkpoint -force -noxdef cw305_top.dcp

catch { report_utilization -file cw305_top_utilization_synth.rpt -pb cw305_top_utilization_synth.pb }
